# Generated by Django 3.1.7 on 2021-03-07 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=7680)], verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=4320)], verbose_name='Высота')),
                ('image', models.ImageField(upload_to='', verbose_name='Файл изображения')),
            ],
        ),
    ]
